services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: sumatik-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # Websockets (for browser/Next.js client)
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
